# -*- coding: utf-8 -*-
"""montyHallGame.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rurlc6rGgCm4xgVyBEha611KXaa5B5nS
"""

import random                                        #import the library random of python3
def montyHallProblem(games=1000):                    #Write a function montyHallProblem(games=1000), a game played 1000 times
    stay_wins = 0                                    #stay wins or wins if you don't switch Initialse to 0
    boxes=["X","Y","Z"]                              #Make a list of three boxes namely 'X', 'Y', 'Z'
    num_boxes=len(boxes)                             #Calculate length of list or number of boxes
    for game in range(games):                        #for loop to play game games (or 1000) times
        prize_box=random.randint(0,num_boxes-1)      #Place prize in random box
        chosen_box=random.randint(0,num_boxes-1)     #Select random box
        if chosen_box== prize_box:                   #if condition - the box you choose has prize
            stay_wins+=1                             #number of wins if you don't switch is increment by 1
    print("Win rate with a don't switch strategy:")  #print "Win rate with a don't switch strategy:"
    print(stay_wins/games)                           #print probability if you don't switch
    print("Win rate with a with a switch strategy:") #print "Win rate with a switch strategy:"
    print(1-(stay_wins/games))                       #print probability if you switch
montyHallProblem()